# Generated by Django 5.0.4 on 2024-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteczka', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
