# Generated by Django 5.0.4 on 2024-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteczka', '0004_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='biblioteczka.genre'),
        ),
    ]
